ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: pgadmin.local
      paths:
        - path: /
          pathType: Prefix
image:
  registry: docker.io
  repository: dpage/pgadmin4
  tag: 4.25

env:
  email: pgadmin
  password: evspassword
persistentVolume:
  size: 1Gi
  existingClaim: pvc-pga
