apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-db
spec:
  storageClassName: db-class
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/run/desktop/mnt/host/c/vshow/mounts/db"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-db
  namespace: vshow
spec:
  storageClassName: db-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pga
spec:
  storageClassName: pga-class
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/run/desktop/mnt/host/c/vshow/mounts/pga"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pga
  namespace: vshow
spec:
  storageClassName: pga-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-files
spec:
  storageClassName: files-class
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/run/desktop/mnt/host/c/vshow/mounts/files"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-files
  namespace: vshow
spec:
  storageClassName: files-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
